spring:
  datasource:
    username: root
    password: CoreKet0629
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seat?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  jpa:
    hibernate:
#    更新或者创建数据表结构
      ddl-auto: update
    show-sql: true

